spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: carFound
        uri: lb://CarFound
        predicates:
        - Path=/cars/**
        filters:
        - RewritePath=/cars/(?<segment>.*), /$\{segment}
        - name: Hystrix
          args:
            name: monitor-cars
            fallbackUri: forward:/fallback/serviceBooks
      - id: serviceA
        uri: lb://car
        predicates:
        - Path=/car/**
        filters:
        - RewritePath=/car/(?<segment>.*), /$\{segment}
        - name: Hystrix
          args:
            name: monitor-car
            fallbackUri: forward:/fallback/serviceA
      - id: truck
        uri: lb://truck
        predicates:
        - Path=/truck/**
        filters:
        - RewritePath=/truck/(?<segment>.*), /$\{segment}
        - name: Hystrix
          args:
            name: monitor-truck
            fallbackUri: forward:/fallback/truck  
      - id: ServiceBike
        uri: lb://bike
        predicates:
        - Path=/bike/**
        filters:
        - RewritePath=/bike/(?<segment>.*), /$\{segment}
        - name: Hystrix
          args:
            name: monitor-bike
            fallbackUri: forward:/fallback/serviceWeather  
        id: ServiceRecall
        uri: lb://recall
        predicates:
        - Path=/recall/**
        filters:
        - RewritePath=/recall/(?<segment>.*), /$\{segment}
        - name: Hystrix
          args:
            name: monitor-recall
            fallbackUri: forward:/fallback/serviceWeather  
      - id: MQActivityService
        uri: lb://offroad
        predicates:
        - Path=/offroad/**
        filters:
        - RewritePath=/act/(?<segment>.*), /$\{segment} 
    consul:
      discovery:
        instanceId: Gateway
        health-check-interval: 5s
      config:
        management: 
          enabled: true
management:
  security: 
    enabled: false
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health
hystrix:
   dashboard:
       proxy-stream-allow-list: "*"
