server:
  port: 8001
  
spring:
  cloud:
    consul:
      discovery:
        instanceId: PrivateCar
        health-check-interval: 5s
      config:
        management: 
          enabled: true
    stream:
      bindings:
        output:
          binder: kafka
          destination: cloudEX
management:
  security: 
    enabled: false
